export type Port = {
  name: string;
  fact: string;
  coordinates: [number, number];
  link: string;
  category: "Major" | "Hidden Gem";
  region: string;
};

export const PORTS: Port[] = [
  {
    name: "Piraeus",
    fact: "Greece’s largest port and the main gateway to Athens.",
    coordinates: [23.6441, 37.9429],
    link: "#services",
    category: "Major",
    region: "Attica",
  },
  {
    name: "Mykonos",
    fact: "Cosmopolitan Cycladic port with iconic windmills and alleys.",
    coordinates: [25.3264, 37.4465],
    link: "#services",
    category: "Major",
    region: "Cyclades",
  },
  {
    name: "Paros",
    fact: "Cycladic harbor famed for Parikia and white-sand beaches.",
    coordinates: [25.1506, 37.0842],
    link: "#services",
    category: "Hidden Gem",
    region: "Cyclades",
  },
  {
    name: "Milos",
    fact: "Volcanic island known for its lunar landscapes and Sarakiniko beach.",
    coordinates: [24.4467, 36.7267],
    link: "#services",
    category: "Hidden Gem",
    region: "Cyclades",
  },
  {
    name: "Folegandros",
    fact: "Quiet Cycladic isle with a cliffside Chora and serene coves.",
    coordinates: [24.9542, 36.6271],
    link: "#services",
    category: "Hidden Gem",
    region: "Cyclades",
  },
  {
    name: "Corfu",
    fact: "Ionian gem with Venetian fortresses and emerald bays.",
    coordinates: [19.9192, 39.6243],
    link: "#services",
    category: "Major",
    region: "Ionian",
  },
  {
    name: "Heraklion",
    fact: "Crete’s capital, minutes from the Palace of Knossos.",
    coordinates: [25.1326, 35.3394],
    link: "#services",
    category: "Major",
    region: "Crete",
  },
  {
    name: "Souda Bay (Chania)",
    fact: "Deep-water bay serving the Venetian city of Chania.",
    coordinates: [24.0746, 35.4886],
    link: "#services",
    category: "Major",
    region: "Crete",
  },
  {
    name: "Agios Nikolaos",
    fact: "Elegant Cretan harbor town set on Mirabello Bay.",
    coordinates: [25.716, 35.191],
    link: "#services",
    category: "Major",
    region: "Crete",
  },
  {
    name: "Santorini",
    fact: "Dramatic caldera views and cliffside villages above the Aegean.",
    coordinates: [25.4325, 36.415],
    link: "#services",
    category: "Major",
    region: "Cyclades",
  },
  {
    name: "Katakolon",
    fact: "Gateway to ancient Olympia, birthplace of the Olympics.",
    coordinates: [21.3172, 37.6578],
    link: "#services",
    category: "Major",
    region: "Peloponnese",
  },
  {
    name: "Thessaloniki",
    fact: "Vibrant northern hub along the Thermaic Gulf promenade.",
    coordinates: [22.9447, 40.6401],
    link: "#services",
    category: "Major",
    region: "Macedonia",
  },
  {
    name: "Volos",
    fact: "Seaside city and gateway to Mount Pelion.",
    coordinates: [22.9482, 39.3598],
    link: "#services",
    category: "Major",
    region: "Thessaly",
  },
  {
    name: "Kavala",
    fact: "Amphitheatrical port city crowned by a Byzantine fortress.",
    coordinates: [24.4126, 40.9355],
    link: "#services",
    category: "Hidden Gem",
    region: "Macedonia",
  },
  {
    name: "Rhodes",
    fact: "Medieval Old Town and sun-drenched Dodecanese beaches.",
    coordinates: [28.2279, 36.4435],
    link: "#services",
    category: "Major",
    region: "Dodecanese",
  },
  {
    name: "Naxos",
    fact: "Largest Cyclades island with a Venetian castle and beaches.",
    coordinates: [25.3763, 37.104],
    link: "#services",
    category: "Major",
    region: "Cyclades",
  },
  {
    name: "Syros",
    fact: "Neoclassical Ermoupoli and refined Cycladic culture.",
    coordinates: [24.9432, 37.4446],
    link: "#services",
    category: "Hidden Gem",
    region: "Cyclades",
  },
  {
    name: "Kefalonia",
    fact: "Ionian island known for Myrtos Beach and limestone caves.",
    coordinates: [20.4893, 38.1754],
    link: "#services",
    category: "Major",
    region: "Ionian",
  },
  {
    name: "Zakynthos",
    fact: "Ionian island famed for Shipwreck Beach and sea caves.",
    coordinates: [20.8977, 37.7811],
    link: "#services",
    category: "Major",
    region: "Ionian",
  },
  {
    name: "Lefkada",
    fact: "Ionian island gateway known for turquoise beaches and sailing routes.",
    coordinates: [20.71, 38.83],
    link: "#services",
    category: "Hidden Gem",
    region: "Ionian",
  },
  {
    name: "Ithaca",
    fact: "Legendary home of Odysseus with a tranquil harbor.",
    coordinates: [20.72, 38.3664],
    link: "#services",
    category: "Hidden Gem",
    region: "Ionian",
  },
  {
    name: "Kithira",
    fact: "Remote island between the Peloponnese and Crete.",
    coordinates: [23.0012, 36.2742],
    link: "#services",
    category: "Hidden Gem",
    region: "Peloponnese",
  },
  {
    name: "Paxos",
    fact: "Small Ionian island with turquoise coves and olive groves.",
    coordinates: [20.1854, 39.2029],
    link: "#services",
    category: "Hidden Gem",
    region: "Ionian",
  },
  {
    name: "Patmos",
    fact: "Dodecanese island of monasteries and sacred history.",
    coordinates: [26.5473, 37.3086],
    link: "#services",
    category: "Major",
    region: "Dodecanese",
  },
  {
    name: "Kos",
    fact: "Lively Dodecanese port with ancient Asklepieion roots.",
    coordinates: [27.2877, 36.8932],
    link: "#services",
    category: "Major",
    region: "Dodecanese",
  },
  {
    name: "Kalymnos",
    fact: "Dodecanese island recognized for sponge-diving heritage.",
    coordinates: [26.9811, 36.9513],
    link: "#services",
    category: "Hidden Gem",
    region: "Dodecanese",
  },
  {
    name: "Leros",
    fact: "Calm Dodecanese harbor with neoclassical and naval history.",
    coordinates: [26.8531, 37.1408],
    link: "#services",
    category: "Hidden Gem",
    region: "Dodecanese",
  },
  {
    name: "Astypalaia",
    fact: "Butterfly-shaped island with a whitewashed hilltop Chora.",
    coordinates: [26.352, 36.548],
    link: "#services",
    category: "Hidden Gem",
    region: "Dodecanese",
  },
  {
    name: "Nisyros",
    fact: "Volcanic island with a walkable caldera.",
    coordinates: [27.1633, 36.6167],
    link: "#services",
    category: "Hidden Gem",
    region: "Dodecanese",
  },
  {
    name: "Karpathos",
    fact: "Southern Aegean island blending mountain villages and beaches.",
    coordinates: [27.228, 35.509],
    link: "#services",
    category: "Hidden Gem",
    region: "Dodecanese",
  },
  {
    name: "Kasos",
    fact: "Small Dodecanese island with an authentic maritime character.",
    coordinates: [26.9197, 35.4225],
    link: "#services",
    category: "Hidden Gem",
    region: "Dodecanese",
  },
  {
    name: "Kastelorizo",
    fact: "Far-eastern Greek island known for its colorful waterfront.",
    coordinates: [29.5904, 36.1483],
    link: "#services",
    category: "Hidden Gem",
    region: "Dodecanese",
  },
  {
    name: "Skiathos",
    fact: "Lush Sporades island with golden beaches.",
    coordinates: [23.4897, 39.1612],
    link: "#services",
    category: "Hidden Gem",
    region: "Sporades",
  },
  {
    name: "Skopelos",
    fact: "Pine-clad Sporades island with classic harbors.",
    coordinates: [23.7287, 39.121],
    link: "#services",
    category: "Hidden Gem",
    region: "Sporades",
  },
  {
    name: "Sifnos",
    fact: "Cycladic island known for pottery and cuisine.",
    coordinates: [24.6974, 36.973],
    link: "#services",
    category: "Hidden Gem",
    region: "Cyclades",
  },
  {
    name: "Serifos",
    fact: "Rugged Cyclades island with a hilltop Chora.",
    coordinates: [24.5212, 37.1484],
    link: "#services",
    category: "Hidden Gem",
    region: "Cyclades",
  },
  {
    name: "Spetses",
    fact: "Elegant Saronic island with neoclassical mansions.",
    coordinates: [23.1573, 37.2614],
    link: "#services",
    category: "Hidden Gem",
    region: "Saronic",
  },
  {
    name: "Hydra",
    fact: "Car-free Saronic island of stone mansions and coves.",
    coordinates: [23.4667, 37.3499],
    link: "#services",
    category: "Hidden Gem",
    region: "Saronic",
  },
  {
    name: "Aegina",
    fact: "Saronic island known for pistachios and the Temple of Aphaia.",
    coordinates: [23.427, 37.7466],
    link: "#services",
    category: "Hidden Gem",
    region: "Saronic",
  },
  {
    name: "Ios",
    fact: "Cycladic island with golden beaches and whitewashed lanes.",
    coordinates: [25.2827, 36.7231],
    link: "#services",
    category: "Hidden Gem",
    region: "Cyclades",
  },
  {
    name: "Amorgos",
    fact: "Dramatic cliffs and the cliffside Hozoviotissa Monastery.",
    coordinates: [25.8616, 36.8332],
    link: "#services",
    category: "Hidden Gem",
    region: "Cyclades",
  },
  {
    name: "Lemnos",
    fact: "North Aegean island with volcanic landscapes and beaches.",
    coordinates: [25.0627, 39.878],
    link: "#services",
    category: "Hidden Gem",
    region: "North Aegean",
  },
  {
    name: "Thassos",
    fact: "Green north Aegean island with marble quarries.",
    coordinates: [24.7097, 40.7783],
    link: "#services",
    category: "Hidden Gem",
    region: "North Aegean",
  },
  {
    name: "Chios",
    fact: "North Aegean island famed for mastic villages.",
    coordinates: [26.1383, 38.3712],
    link: "#services",
    category: "Hidden Gem",
    region: "North Aegean",
  },
  {
    name: "Ikaria",
    fact: "North Aegean island famed for longevity and laid-back rhythm.",
    coordinates: [26.2945, 37.613],
    link: "#services",
    category: "Hidden Gem",
    region: "North Aegean",
  },
  {
    name: "Lesvos",
    fact: "North Aegean island centered on the historic port of Mytilene.",
    coordinates: [26.5552, 39.106],
    link: "#services",
    category: "Hidden Gem",
    region: "North Aegean",
  },
  {
    name: "Samothrace",
    fact: "Dramatic north Aegean island with rugged peaks and waterfalls.",
    coordinates: [25.469, 40.472],
    link: "#services",
    category: "Hidden Gem",
    region: "North Aegean",
  },
  {
    name: "Itea",
    fact: "Gateway port to Delphi on the Gulf of Corinth.",
    coordinates: [22.422, 38.434],
    link: "#services",
    category: "Hidden Gem",
    region: "Central Greece",
  },
  {
    name: "Kalamata",
    fact: "Peloponnese port known for olives and a seaside promenade.",
    coordinates: [22.1142, 37.0379],
    link: "#services",
    category: "Hidden Gem",
    region: "Peloponnese",
  },
  {
    name: "Nafplio",
    fact: "Romantic coastal town and the first capital of modern Greece.",
    coordinates: [22.8016, 37.5673],
    link: "#services",
    category: "Hidden Gem",
    region: "Peloponnese",
  },
  {
    name: "Pylos",
    fact: "Historic bay near Navarino and the Old Fortress.",
    coordinates: [21.6962, 36.9124],
    link: "#services",
    category: "Hidden Gem",
    region: "Peloponnese",
  },
  {
    name: "Gytheio",
    fact: "Laconian port with a neoclassical waterfront.",
    coordinates: [22.565, 36.755],
    link: "#services",
    category: "Hidden Gem",
    region: "Peloponnese",
  },
  {
    name: "Monemvasia",
    fact: "Medieval fortress town carved into a massive sea rock.",
    coordinates: [23.056, 36.6876],
    link: "#services",
    category: "Hidden Gem",
    region: "Peloponnese",
  },
  {
    name: "Igoumenitsa",
    fact: "Ionian gateway to Epirus and the Adriatic.",
    coordinates: [20.265, 39.503],
    link: "#services",
    category: "Hidden Gem",
    region: "Epirus",
  },
];
